# fly.toml app configuration file generated for autou-new on 2025-08-28T21:52:25-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'autou-new'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
source="data"
destination="/app/db"

